### ISSUE TITLE
Package name conflicts with system framework

### ISSUE THREAD

**Issue by MarkVillacampa** [0xLeif/Network#4]
Hello!

This package conflicts with an Apple system framework called [Networking](https://developer.apple.com/documentation/network). This can cause complication issues when another package in the same app depends on the system framework with the same name.

These are the ingredients to reproduce:

- One package with a name that matches a system framework: e.g. "Network", and with a minimum OS version higher than what the system framework with the same name has.
- Another module that depends, explicitly or implicitly, on the system framework mentioned before, and has a minimum version lower than the conflicting package.

When both packages get added to an app, and the app gets compiled, each package produces a swiftmodule file in the following path:
`~/Library/Developer/Xcode/DerivedData/YourApp-ogcxwvzvuguxo/Build/Products/Debug-iphoneos/PACKAGE_NAME.swiftmodule/arm64-apple-ios.swiftmodule`

That path gets added to the swiftmodule lookup path when compiling other packages.

Xcode comes with prebuilt swiftmodules for all system frameworks (See `find /Applications/Xcode.app -iname "*swiftmodule"`) but the previous path gets preference because it contains modules built by the app, which reasonably get used more often. You can see where this is going.

When Xcode tries to compile the package that depends on the system framework, it first looks for a swiftmodule with that name in the app's build directory. It finds the one from our conflicting package, and tries to use it. But because our package has a lower minimum version, it fails.

I'd encourage you to rename the package in order to avoid this issue.

![image](https://github.com/0xLeif/Network/assets/1014118/510856f0-46ae-469f-bc56-09deb9635dc7)

**Comment by 0xLeif** [comment]
Will probably merge this project into [Later](https://github.com/0xLeif/Later). Thank you for bringing this issue up!

**Comment by 0xLeif** [comment]
I’ve moved this code into the Later project. [Later@2.0.0](https://github.com/0xLeif/Later/releases/tag/2.0.0) has all of the Network code in it.
